# Generated by Django 4.1.3 on 2022-12-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBmanagement', '0002_client_staff_salary_users_staff_idsalary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('iddetails', models.IntegerField(db_column='idOrder', primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=45, null=True)),
                ('buildingnumber', models.CharField(blank=True, db_column='BuildingNumber', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('idinsurance', models.IntegerField(db_column='idInsurance', primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('cost', models.IntegerField(blank=True, db_column='Cost', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': 'Insurance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('idorder', models.IntegerField(db_column='idOder', primary_key=True, serialize=False)),
                ('dateoforder', models.DateField(blank=True, db_column='DateOfOrder', null=True)),
                ('datestart', models.DateField(blank=True, db_column='DateStart', null=True)),
                ('dateend', models.DateField(blank=True, db_column='DateEnd', null=True)),
                ('idclient', models.ForeignKey(blank=True, db_column='idClient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.client')),
                ('iddeliverydetail', models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.details')),
            ],
            options={
                'db_table': 'Orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('idservicetype', models.IntegerField(db_column='idServiceType', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('cost', models.IntegerField(blank=True, db_column='Cost', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'ServiceType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservice', models.IntegerField(db_column='idService', primary_key=True, serialize=False)),
                ('dateofstart', models.DateField(blank=True, db_column='DateOfStart', null=True)),
                ('dateofend', models.DateField(blank=True, db_column='DateOfEnd', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('idcar', models.ForeignKey(blank=True, db_column='idCar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.cars')),
            ],
            options={
                'db_table': 'Service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idpayment', models.IntegerField(db_column='idPayment', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
                ('amounttopay', models.IntegerField(blank=True, db_column='AmountToPay', null=True)),
                ('dateofpayment', models.DateField(blank=True, db_column='DateOfPayment', null=True)),
                ('amountpayed', models.IntegerField(blank=True, db_column='AmountPayed', null=True)),
                ('idorder', models.ForeignKey(blank=True, db_column='idOrder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.orders')),
            ],
            options={
                'db_table': 'Payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listofstaff',
            fields=[
                ('idlistofstaff', models.IntegerField(db_column='idListOfStaff', primary_key=True, serialize=False)),
                ('idservice', models.ForeignKey(blank=True, db_column='idService', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.service')),
                ('idstaff', models.ForeignKey(blank=True, db_column='idStaff', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.staff')),
            ],
            options={
                'db_table': 'ListOfStaff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listofservices',
            fields=[
                ('idlistofservice', models.IntegerField(db_column='idListOfService', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('idservice', models.ForeignKey(blank=True, db_column='idService', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.service')),
                ('idservicetype', models.ForeignKey(blank=True, db_column='idServiceType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.servicetype')),
            ],
            options={
                'db_table': 'ListOfServices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listofcars',
            fields=[
                ('idlistofcars', models.OneToOneField(db_column='idInsurance', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DBmanagement.insurance')),
                ('idcar', models.ForeignKey(blank=True, db_column='idCar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.cars')),
                ('idorder', models.ForeignKey(blank=True, db_column='idOrder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DBmanagement.orders')),
            ],
            options={
                'db_table': 'ListOfCars',
                'managed': True,
            },
        ),
    ]
