# Generated by Django 4.1.3 on 2022-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBmanagement', '0003_details_insurance_orders_servicetype_service_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcars',
            name='idlistofcars',
            field=models.IntegerField(db_column='idInsurance', primary_key=True, serialize=False),
        ),
    ]
