# Generated by Django 4.1.3 on 2022-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBmanagement', '0004_alter_listofcars_idlistofcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('idorder', models.AutoField(db_column='idOrder', primary_key=True, serialize=False)),
                ('amountofstar', models.IntegerField(blank=True, db_column='AmountOfStar', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': True,
            },
        ),
    ]
